In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Mall_Customers.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Genre                   200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [2]:
df.head()

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [3]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [4]:
df.Age.mean()

np.float64(38.85)

In [5]:
df.Age.min()

18

In [6]:
df['Age'].max()

70

In [7]:
df.Age.std()

13.969007331558883

In [8]:
df.Age.median()

36.0

In [9]:
df.Genre.mode()

0    Female
Name: Genre, dtype: object

In [10]:
print(df.groupby(["Genre"]).mean())

        CustomerID        Age  Annual Income (k$)  Spending Score (1-100)
Genre
Female   97.562500  38.098214           59.250000               51.526786
Male    104.238636  39.806818           62.227273               48.511364

In [11]:
df.shape

(200, 5)

In [12]:
df.dtypes

CustomerID                 int64
Genre                     object
Age                        int64
Annual Income (k$)         int64
Spending Score (1-100)     int64
dtype: object

In [13]:
summary= df.groupby('Genre')['Annual Income (k$)'].describe()
print(summary)

        count       mean        std   min    25%   50%    75%    max
Genre
Female  112.0  59.250000  26.011952  16.0  39.75  60.0  77.25  126.0
Male     88.0  62.227273  26.638373  15.0  45.50  62.5  78.00  137.0

In [14]:
summary= df.groupby('Age')['Annual Income (k$)'].describe()
print(summary)

     count        mean        std   min     25%    50%     75%    max
Age
18     4.0   51.250000  14.056434  33.0   44.25   53.5   60.50   65.0
19     8.0   57.000000  20.632845  15.0   47.50   63.5   67.25   81.0
20     5.0   41.600000  24.815318  16.0   21.00   37.0   61.00   73.0
21     5.0   38.800000  19.018412  15.0   30.00   33.0   54.00   62.0
22     3.0   31.333333  22.278540  17.0   18.50   20.0   38.50   57.0
23     6.0   41.500000  23.441416  16.0   20.75   41.5   60.00   70.0
24     4.0   39.250000  16.357975  20.0   33.50   38.5   44.25   60.0
25     3.0   57.666667  29.263174  24.0   48.00   72.0   74.50   77.0
26     2.0   58.000000   5.656854  54.0   56.00   58.0   60.00   62.0
27     6.0   63.166667  18.400181  40.0   49.50   63.5   75.25   88.0
28     4.0   85.250000  11.615363  76.0   76.75   82.0   90.50  101.0
29     5.0   63.600000  28.866936  28.0   40.00   73.0   79.00   98.0
30     7.0   76.142857  39.612408  19.0   56.00   78.0   93.50  137.0
31     8.0   48.375000  23.323425  17.0   35.50   41.5   70.50   81.0
32    11.0   87.181818  26.809768  48.0   74.00   77.0  100.00  137.0
33     3.0   80.333333  35.837597  42.0   64.00   86.0   99.50  113.0
34     5.0   79.000000  15.968719  58.0   78.00   78.0   78.00  103.0
35     9.0   46.666667  38.632888  18.0   21.00   24.0   74.00  120.0
36     6.0   81.000000  22.556595  37.0   85.50   87.0   87.00  103.0
37     3.0   65.000000  40.112342  20.0   49.00   78.0   87.50   97.0
38     6.0   74.500000  20.462160  54.0   64.75   69.0   76.25  113.0
39     3.0   72.666667   4.725816  69.0   70.00   71.0   74.50   78.0
40     6.0   61.666667  19.551641  29.0   55.50   64.5   70.50   87.0
41     2.0  101.000000   2.828427  99.0  100.00  101.0  102.00  103.0
42     2.0   60.000000  36.769553  34.0   47.00   60.0   73.00   86.0
43     3.0   65.666667  15.695010  48.0   59.50   71.0   74.50   78.0
44     2.0   75.500000   3.535534  73.0   74.25   75.5   76.75   78.0
45     3.0   69.333333  50.767444  28.0   41.00   54.0   90.00  126.0
46     3.0   59.000000  36.755952  25.0   39.50   54.0   76.00   98.0
47     6.0   70.166667  27.694163  43.0   51.75   65.5   76.25  120.0
48     5.0   58.200000  13.700365  39.0   54.00   60.0   61.00   77.0
49     7.0   51.000000  12.884099  33.0   40.50   54.0   62.00   65.0
50     5.0   58.600000  18.420098  40.0   43.00   58.0   67.00   85.0
51     2.0   55.500000  16.263456  44.0   49.75   55.5   61.25   67.0
52     2.0   55.500000  45.961941  23.0   39.25   55.5   71.75   88.0
53     2.0   39.500000   9.192388  33.0   36.25   39.5   42.75   46.0
54     4.0   59.750000  30.998656  28.0   42.25   55.0   72.50  101.0
55     1.0   57.000000        NaN  57.0   57.00   57.0   57.00   57.0
56     1.0   79.000000        NaN  79.0   79.00   79.0   79.00   79.0
57     2.0   64.500000  14.849242  54.0   59.25   64.5   69.75   75.0
58     2.0   54.000000  48.083261  20.0   37.00   54.0   71.00   88.0
59     4.0   65.250000  21.792583  43.0   51.25   62.5   76.50   93.0
60     3.0   43.333333  11.547005  30.0   40.00   50.0   50.00   50.0
63     2.0   56.500000  12.020815  48.0   52.25   56.5   60.75   65.0
64     1.0   19.000000        NaN  19.0   19.00   19.0   19.00   19.0
65     2.0   50.500000  17.677670  38.0   44.25   50.5   56.75   63.0
66     2.0   63.000000   0.000000  63.0   63.00   63.0   63.00   63.0
67     4.0   45.500000  18.699376  19.0   40.00   50.5   56.00   62.0
68     3.0   56.666667   7.767453  48.0   53.50   59.0   61.00   63.0
69     1.0   44.000000        NaN  44.0   44.00   44.0   44.00   44.0
70     2.0   47.500000   2.121320  46.0   46.75   47.5   48.25   49.0