In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/Toyota.csv")
print(df)

      Unnamed: 0  Price   Age     KM FuelType   HP  MetColor  Automatic    CC  \
0              0  13500  23.0  46986   Diesel   90       1.0          0  2000
1              1  13750  23.0  72937   Diesel   90       1.0          0  2000
2              2  13950  24.0  41711   Diesel   90       NaN          0  2000
3              3  14950  26.0  48000   Diesel   90       0.0          0  2000
4              4  13750  30.0  38500   Diesel   90       0.0          0  2000
...          ...    ...   ...    ...      ...  ...       ...        ...   ...
1431        1431   7500   NaN  20544   Petrol   86       1.0          0  1300
1432        1432  10845  72.0     ??   Petrol   86       0.0          0  1300
1433        1433   8500   NaN  17016   Petrol   86       0.0          0  1300
1434        1434   7250  70.0     ??      NaN   86       1.0          0  1300
1435        1435   6950  76.0      1   Petrol  110       0.0          0  1600

      Doors  Weight
0     three    1165
1         3    1165
2         3    1165
3         3    1165
4         3    1170
...     ...     ...
1431      3    1025
1432      3    1015
1433      3    1015
1434      3    1015
1435      5    1114

[1436 rows x 11 columns]

In [3]:
df.head(5)

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500,23.0,46986,Diesel,90,1.0,0,2000,three,1165
1,1,13750,23.0,72937,Diesel,90,1.0,0,2000,3,1165
2,2,13950,24.0,41711,Diesel,90,NaN,0,2000,3,1165
3,3,14950,26.0,48000,Diesel,90,0.0,0,2000,3,1165
4,4,13750,30.0,38500,Diesel,90,0.0,0,2000,3,1170

In [4]:
df.isnull().sum()

Unnamed: 0      0
Price           0
Age           100
KM              0
FuelType      100
HP              0
MetColor      150
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1436 non-null   int64
 1   Price       1436 non-null   int64
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object
 4   FuelType    1336 non-null   object
 5   HP          1436 non-null   object
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64
 8   CC          1436 non-null   int64
 9   Doors       1436 non-null   object
 10  Weight      1436 non-null   int64
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB

In [6]:
df.describe()

,Unnamed: 0,Price,Age,MetColor,Automatic,CC,Weight
count,1436.000000,1436.000000,1336.000000,1286.000000,1436.000000,1436.000000,1436.00000
mean,717.500000,10730.824513,55.672156,0.674961,0.055710,1566.827994,1072.45961
std,414.681806,3626.964585,18.589804,0.468572,0.229441,187.182436,52.64112
min,0.000000,4350.000000,1.000000,0.000000,0.000000,1300.000000,1000.00000
25%,358.750000,8450.000000,43.000000,0.000000,0.000000,1400.000000,1040.00000
50%,717.500000,9900.000000,60.000000,1.000000,0.000000,1600.000000,1070.00000
75%,1076.250000,11950.000000,70.000000,1.000000,0.000000,1600.000000,1085.00000
max,1435.000000,32500.000000,80.000000,1.000000,1.000000,2000.000000,1615.00000

In [7]:
df.dtypes

Unnamed: 0      int64
Price           int64
Age           float64
KM             object
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [8]:
df.dropna()

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500,23.0,46986,Diesel,90,1.0,0,2000,three,1165
1,1,13750,23.0,72937,Diesel,90,1.0,0,2000,3,1165
3,3,14950,26.0,48000,Diesel,90,0.0,0,2000,3,1165
4,4,13750,30.0,38500,Diesel,90,0.0,0,2000,3,1170
5,5,12950,32.0,61000,Diesel,90,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...,...
1425,1425,7950,80.0,??,Petrol,86,1.0,0,1300,4,1000
1429,1429,8950,78.0,24000,Petrol,86,1.0,1,1300,5,1065
1430,1430,8450,80.0,23000,Petrol,86,0.0,0,1300,3,1015
1432,1432,10845,72.0,??,Petrol,86,0.0,0,1300,3,1015
1435,1435,6950,76.0,1,Petrol,110,0.0,0,1600,5,1114

In [9]:
mean_val=df['Age'].mean()
df['Age']=df['Age'].fillna(mean_val)
mean_val=df['MetColor'].mean()
df['MetColor']=df['MetColor'].fillna(mean_val)
df.isnull().sum()

Unnamed: 0      0
Price           0
Age             0
KM              0
FuelType      100
HP              0
MetColor        0
Automatic       0
CC              0
Doors           0
Weight          0
dtype: int64

In [10]:
df['Price']=df['Price'].astype('float')
df.dtypes

Unnamed: 0      int64
Price         float64
Age           float64
KM             object
FuelType       object
HP             object
MetColor      float64
Automatic       int64
CC              int64
Doors          object
Weight          int64
dtype: object

In [11]:
df.head(5)

,Unnamed: 0,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,0,13500.0,23.0,46986,Diesel,90,1.000000,0,2000,three,1165
1,1,13750.0,23.0,72937,Diesel,90,1.000000,0,2000,3,1165
2,2,13950.0,24.0,41711,Diesel,90,0.674961,0,2000,3,1165
3,3,14950.0,26.0,48000,Diesel,90,0.000000,0,2000,3,1165
4,4,13750.0,30.0,38500,Diesel,90,0.000000,0,2000,3,1170